### ISSUE TITLE
 🐛 Typo in Work page

### ISSUE THREAD

**Issue by reemhamz** [robsterlini/robsterlini-frontend#72]
You popped into my mind the other day and thought I'd check on your awesome website! I found a tiny little typo in your [work page](https://robsterlini.co.uk/work), under your experience at Fueled ⛽️. 

### What’s up doc?
Typo, should say `fantastic engineers` but instead says `fantastic enginners`.
### Is there a proposed fix?
just a nice and simple typo

:bug:

I've always loved seeing your progressions and creative website. Hope you're well otherwise, Rob! 🚀💫

**Comment by robsterlini** [comment]
Thanks for flagging this Reem!! Have bundled the fix into #74. I am well thanks, I hope you are too!
